
services:
  postgres:
    image: postgres:15
    container_name: job_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: jobdb
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: job_pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "6060:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - job-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: job_zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped
    networks:
      - job-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - job-network

  config-server-ms:
    image: samnangprod/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      - job-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: samnangprod/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - job-network

  companyms:
    image: samnangprod/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - job-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: samnangprod/jobms:latest
    container_name: job.txt
    ports:
      - 8082:8082
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - job-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: samnangprod/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - job-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-ms:
    image: samnangprod/gateway-ms:latest
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - job-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  job-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data: