spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: job_service
              uri: lb://JOB-SERVICE
              predicates:
                - Path=/jobs
                - Path=/jobs/**

            - id: company_service
              uri: http://localhost:8081
              predicates:
                - Path=/companies
                - Path=/companies/**

            - id: review_service
              uri: http://localhost:8083
              predicates:
                - Path=/reviews
                - Path=/reviews/**

            - id: eureka_server
              uri: http://localhost:8761
              filters:
                - SetPath=/
              predicates:
                - Path=/eureka/main
            - id: eureka_server-static
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO