spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://postgres:5432/jobdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

job-service:
  url: "http://job:8082"

company-service:
  url: "http://company:8081"

review-service:
  url: "http://review:8083"

  cloud:
    openfeign:
      micrometer:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://servicereg:8761/eureka/"

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"


